supabase_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRudnRobWdlYWZndnFoemJldGp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5NzU1NDUsImV4cCI6MjA2MDU1MTU0NX0.DE7K3Uzful-ilzK0uUd0mh9Ck5ggc8toeMqocnpT8uQ"
supabase_url = "https://tnvthmgeafgvqhzbetjz.supabase.co"
