supabase_url = "https://upldspsevplwwlacptdn.supabase.co"
supabase_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwbGRzcHNldnBsd3dsYWNwdGRuIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1OTkwMzEyNCwiZXhwIjoyMDc1NDc5MTI0fQ.uS0AXIf31U1XQri2IoJpLKBtqWzLXBCRp0cJISuhKE0"

