supabase_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwbGRzcHNldnBsd3dsYWNwdGRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk5MDMxMjQsImV4cCI6MjA3NTQ3OTEyNH0.cdqA0K1vxmxjT0sYgdHOowvJyXPHUwCdFEU4QQG7cBU"
supabase_url = "https://upldspsevplwwlacptdn.supabase.co"

